### PR TITLE
Add possibility to use own target branch

### PR DESCRIPTION
**Pull request by spoonerWeb**
Should be an option if one want to merge into a feature branch

### CODE REVIEW

**Comment by tmaier** [comment]
Hi, 

I like it! However, my project is just a fork focusing on the GotLab/Docker part.

Could you consider to provide this merge request to the upstream repo?

Thanks!

Tobias

**Comment by tmaier** [comment]
FYI @rpadovani

**Comment by spoonerWeb** [comment]
Hey,

I realized that there is a bug in the patch and I worked the whole afternoon to create a docker image for my purposes.
My issue is:

1. I have a PHP web project built with composer
1. I use GitLab and want to add a scheduled pipeline to look for minor bugfix updates
1. When there is a change in the library, the build commits the changes and pushes it into a feature branch
1. Then a MR will be created

Your docker image is a good start and I want to thank you for this inspiration. I changed mainly the shell script to fulfill my needs. You can see the changes in https://git.spooner.io/docker/gitlab-auto-merge-request. Feel free to take some or all changes I did.

It's not finished yet and I'm in the middle of testing it with my own website. I can ping you when I feel I'm finished :wink:

**Comment by spoonerWeb** [comment]
BTW: I reverted this change in my repository, because I wanted to configure the source branch (not the target branch). So, I wouldn't merge this.

**Pull request closed without merging**
